### ISSUE TITLE
What to decay in generators by default: let pi0s decay

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#87] opened 2022-10-26 08:45 UTC
The impy default at the moment is to not decay pi0s.

This is not a good default, because it does not match what we understand as final-state particles at colliders. I would like to change this and let pi0s decay by default. Final state particles should be those which have a life-time longer than 30 ps, as described in this public ALICE note https://inspirehep.net/literature/1945324, whose definition agrees with the LHC-wide *CERN Minimum Bias and Underlying Event working group*.

Naturally, it is `MCRun.set_stable` should be supported by all models to change this at run-time for each model as desired by the user.

**Comment by afedynitch** [comment] 2022-10-27 13:40
I think it is fine to change this except that most generators do not decay pi0 by default. QGSJET doesn't do decays. I would be fine with having a consistent setting but see #86 a somewhat deeper explanation about the decays in generators. If we want that generators are extremely strict about this, then we have a flavor of a previous Pythia8 "mod" called [PythiaDecayAfterBurner](https://github.com/impy-project/impy/blob/main/tests/fixme_decay_afterburner.py).

**Comment by HDembinski** [comment] 2022-10-28 08:08
If QGSJet does not decay pi0s this, we should add a little code to do it for QGSJet to unify the behavior of all models. If it is only for pi0, that shouldn't be hard to write even without the PythiaDecayAfterBurner. The AfterBurner is a very general and nice solution, but probably slow because we have to copy particles between stacks, initialize another model, etc.

**Comment by HDembinski** [comment] 2022-10-28 08:15
> most generators do not decay pi0 by default

I don't know about the default setting in the model, but the majority of models can decay pi0.

EPOS, SYBILL, PYTHIA, DPMJet, Phojet.

It is probably only QGSJet that cannot. I should check what CRMC does when it generates QGSJet events.

**Comment by HDembinski** [comment] 2022-11-25 14:14
I understand the issue now better since my work on #89 . I will make a C++ equivalent of the PythiaDecayAfterBurner to decay particles which are not decayed by certain models which uses Pythia8.

**Comment by HDembinski** [comment] 2023-07-05 08:40
@afedynitch @jncots We need to move forward with this, because the first people are tripping over this issue. We need to implement at least a partial fix ASAP.

Currently, SIBYLL and QGSJet consider all long-lived particles as stable by default. So when you request status == 3, you get K_S and Lambda. EPOS and Pythia decay everything by default, so you won't get K_S and Lambda as final state. We need to unify this so that users get the same output for every model.

For models which support `set_stable` it is easy to do, we just need to call this with the appropriate PIDs when constructing the model.

Making all long-lived particles (tau > 30 ps) stable is what you need for most analyses at colliders and what you need for cosmic ray studies, so it is a good default. Users can still manually call `set_stable` to decay particles. The point is to make the default - when you do not call set_stable manually - to be the same between models.

**Comment by afedynitch** [comment] 2023-07-05 09:05
OK, I agree that this must be solved on short term. In impy, I had this machinery in place. It used the `particletools` package, which knew what kind of PIDs are known by an interaction model. Idk, what has replaced this functionality, since there is no or not much "exception handling" by the pid conversion routines.

For the interaction models it works in following way:
PYTHIA6, DPMJET, PHOJET: Settings in PYTHIA6 common block (all know the same particles), also there is the tau-stable definition from Pythia 6, which could override some definitions. 
SOPHIA: Almost same but using PYTHIA6's predecessor JETSET common blocks (there might be less particles defined there)
Pythia8: Through it's regular setting methods
QGSJet: No settings, all particles stable (need afterburner for rho0, eta and K0). There are no rare particles in the model, only those listed in the conversion routines in our middle layer.
EPOS-LHC: Don't know really, but the idtrafo subroutine has some exception handling. We could use it to generate a list of accepted particles write out their codes (because idtrafo is actually not fast).
UrQMD: I have typed the tables from the manual into particletools a while ago and used it. 

We could generate a list of known particles from the particletools package for the exotic generators. For PYTHIA6 I could figure out which common blocks would know all the PDG IDs.

In DPMJET there is also another problem #156, where stable definitions would be overridden between events for nuclei. I know where the problem is coming from but was unable to fix this timewise. I can work on this after the ICRC proceedings deadline until then overbooked.

**Comment by HDembinski** [comment] 2023-07-05 09:23
Sorry @afedynitch I was mistaken. Actually we do what I propose already, we already have the function _set_final_state_particles to unify which performs this step. I was trying to understand some issue that came up when Julian in my group used chromo to do some studies, and I thought it was because of the different definitions of final states.

So it is actually not so bad, we just need to document the current status better. We can only fix the QGSJet issue with the pi0 when we implement the decay afterburner eventually. This has not such high priority. We should also document the following idiosyncrasies:
- the QGSJets do not genera any Omega-, Xi0, Xi+, Xi-, Sigma-, Sigma+ and cc.
- Sibyll21 does not generate Omega- and cc.
- UrQMD34 does not generate any KS

**Comment by afedynitch** [comment] 2023-07-05 09:28
Happy to hear that.

QGSJet should also produce rho, and QGSJet01 charm. So there must be a few more particles to forward to the afterburner. In UrQMD, we have [another mechanism in place](https://github.com/impy-project/chromo/blob/b4224bfcbb88e7092780772fedca5b2055dd6d44/src/fortran/urqmd-3.4/chromo_urqmd.f#L67) to convert K0 and K0bar into KS/KL.

**Comment by HDembinski** [comment] 2023-07-05 09:42
> In UrQMD, we have [another mechanism in place](https://github.com/impy-project/chromo/blob/b4224bfcbb88e7092780772fedca5b2055dd6d44/src/fortran/urqmd-3.4/chromo_urqmd.f#L67) to convert K0 and K0bar into KS/KL.

This does not seem to work then. I am currently writing a new unit test to check this for all generators.

**Comment by HDembinski** [comment] 2023-07-05 09:45
DpmjetIII191 seems to generate no Omega+, but generates Omega-.

**Comment by afedynitch** [comment] 2023-08-23 03:53
While the issue is fixed for most of the generators in #160 , the remaining one is QGSjet.

I have checked what can be done. There is a two-body decay function in QGSjet. It's simple and could be abused. But QGSjet doesn't know photons at all. Also masses in QGS are set by hand to some rounded values. So it needs some careful decisions.

Before closing this one, we need to verify if #167 conserves energy (@jncots ) if the masses are provided by QGSJet.

**Comment by afedynitch** [comment] 2023-08-23 08:32
According to @jncots, energy conservation seems to hold in QGSjet + DecayHandler. Then #167 will close this.

**Closed** 2023-09-14 08:16 UTC
